apiVersion: v1
kind: Service
metadata:
  name: logretriever-webserver
  namespace: logging-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: logretriever-webserver
  type: NodePort
